/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#10131a',
        'surface-dim': '#10131a',
        'surface-bright': '#363941',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d2027',
        'surface-container-high': '#272a31',
        'surface-container-highest': '#32353c',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#e1e2ec',
        'inverse-on-surface': '#2e3038',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        'primary': '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        'secondary': '#4cd7f6',
        'on-secondary': '#003640',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        'tertiary': '#d0bcff',
        'on-tertiary': '#3c0091',
        'tertiary-container': '#a078ff',
        'on-tertiary-container': '#340080',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',
        'background': '#10131a',
        'on-background': '#e1e2ec',
        'surface-variant': '#32353c',
      },
      fontFamily: {
        sans: ['Rubik', 'Outfit', 'sans-serif'],
        'headline-xl': ['Rubik', 'sans-serif'],
        'headline-lg': ['Rubik', 'sans-serif'],
        'headline-md': ['Rubik', 'sans-serif'],
        'body-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Outfit', 'sans-serif'],
        'body-sm': ['Outfit', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      animation: {
        'spin-slow': 'spin 8s linear infinite',
      },
    },
  },
  plugins: [],
}
